/* Chapter 21 - AddressBook */
/* CAddressBookApp.h */



/****************************************************************************** CAddressBookApp.h
Header File For CAddressBookApp Application Class Copyright © 1994 Neil Rhodes and Julie McKeehan. All rights reserved. Generated by Visual Architect_ 7:59 AM Sun, Apr 3, 1994
This file is only generated once. You can modify it by redefining in the placeholder definitions and adding any new methods and data members you want.
If you change the name of the application, a fresh version of this file will be generated. If you have made any changes to the file with the old name, you will have to copy those changes to the new file by hand.
******************************************************************************/



#pragma once

#include "x_CAddressBookApp.h" 
#include <CDialog.h>

class CAddressBookApp : public x_CAddressBookApp 
{
public:
    TCL_DECLARE_CLASS
    void ICAddressBookApp(void);
    virtual void ForceClassReferences(void);
    virtual void DoCommand(long theCommand);

    // Remove this function if you do not have 
    // multiple document types

    virtual OSType GetDocTypeFromDialog(CDialogDirector *dialog);

};

// File Types
//
// Change the #defines below to reflect the file types 
// your application actually creates or opens

#define kNumFileTypes 1
#define kFileType1    'ADDR'
#define kFileType2    'TEXT'
#define kFileType3    'TEXT'
#define kFileType4    'TEXT'
