/* Chapter 21 - AddressBook */
/* CAddressBookDoc.h */

/****************************************************************************** CAddressBookDoc.h
Header File For CAddressBookDoc Document Class
Copyright © 1994 Neil Rhodes and Julie McKeehan. All rights reserved.

 Generated by Visual Architect_ 7:59 AM Sun, Apr 3, 1994
This file is only generated once. You can modify it by extending the placeholder definitions and adding any new methods and
data members you want.
If you change the name of the document class, a fresh version of this file will be generated. If you have made any changes to the file
with the old name, you will have to copy those changes to the new file by hand.
******************************************************************************/


#pragma once
#include "x_CAddressBookDoc.h"
#include "CStreamableDatabase.h"
#include "Entry.h"

class CAddressBookDoc public x_CAddressBookDoc
{ public:

TCL_DECLARE_CLASS
void ICAddressBookDoc(void);
virtual void MakeNewContents(void); 
virtual void ContentsToWindow(void);
virtual Titerator *CreateDatabaselterator(); 
virtual void AddEntry(TEntry *entry);
canst long kReasonNewEntry =1001;
// If you have multiple document classes, you must change
// the file type below to the appropriate type for this class. 
// If not, this #define is not used.

};
#define CAddressBookDocFType 'ADDR'


