/* Chapter 21 - AddressBook */
/* CAddressBookPane.h */

/****************************************************************************** CAddressBookPane.h

Header for CAddressBookPane Panorama/EditText Class 

Copyright © 1994 Neil Rhodes and Julie McKeehan. All rights reserved.

Generated by Visual Architect_ 8:16 AM Sun, Apr 3, 1994

This file is only generated once. You can modify it by filling
in the placeholder functions and adding any new functions you want.

If you change the name of the document class, a fresh version of this file will be generated. If you have made any changes to the file
with the old name, you will have to copy those changes to the new file by hand.
******************************************************************************/

#pragma once

#include "x_CAddressBookPane.h" 
#include "Database.h"
#include "CAddressBookDoc.h"

class CAddressBookPane : public x_CAddressBookPane
{
public: 
    TCL_DECLARE_CLASS
virtual void UpdateMenus();

virtual void DoCmdGoForward(void);
virtual void DoCmdGoBackward(void);
virtual void DoCmdGoToBeginning(void);
virtual void DoCmdGoToEnd(void);
virtual void InitialSetup(CAddressBookDoc *doc);

protected:
    virtual void ProviderChanged(CCollaborator *aProvider, long reason, void* info);

private:
    virtual void UpdateEntryData(void);
    TIterator *fAddressBookIterator; 
    CAddressBookDoc *GetAddressBookDoc();
    CAddressBookDoc *fAddressBookDoc;
};


