/* Chapter 21 - AddressBook */
/* CNewEntryDialog.h */


/****************************************************************************** 
CNewEntryDialog.h

CNewEntryDialog Dialog Director Class

Copyright © 1994 Neil Rhodes and Julie McKeehan. All rights reserved.

Generated by Visual Architect_ 3:16 PM Sun, Apr 3, 1994

This file is only generated once. You can modify it by filling
in the placeholder functions and adding any new functions you want.

If you change the name of the dialog class, a fresh version of this file will be generated. If you have made any changes to the file



 with the old name, you will have to copy those changes to the new file by hand.
******************************************************************************/
#pragma once

#include "x_CNewEntryDialog.h"

class CDirectorOwner;

class CNewEntryDialog public x_CNewEntryDialog {
public:
    TCL_DECLARE_CLASS
    // Insert your own public data members here
    void ICNewEntryDialog(CDirectorOwner *aSupervisor);

protected:
    virtual void BeginData(CNewEntryDialogData *initial); 
    virtual void EndData(CNewEntryDialogData *final);
};
