/* Chapter 21 - AddressBook */
/* ItsContentsClass.h */


/****************************************************************************** 

ItsContentsClass.h

Define class of csaver itsContents variable

Copyright © 1994 Neil Rhodes and Julie McKeehan. All rights reserved. 

Generated by Visual Architect_ 7:47 AM Sun, Apr 3, 1994

This file is only generated once.

Change CCollaborator below to the actual class of
your itsContents object ******************************************************************************/

#pragma once

#include "CStreamableDatabase.h"

#define ITSCONTENTSCLASS CStreamableDatabase 

#ifdef GENERATE_TEMPLATE

#pragma template CSaver<CStreamableDatabase> 

#endif

