/* Chapter 21 - AddressBook */
/* NewEntryDialogItems.h */



I
****************************************************************************************************** 

NewEntryDialog Item Constants

Copyright [cw]1994 Neil Rhodes and Julie McKeehan. All rights reserved. 

Generated by Visual Architect{tm}

This file is rewritten each time you generate code. You should not make changes to this file.

If you want to change how Visual Architect generates this file, you can chage the template for this file. It is Items.h in the Visual Architect Templates folder.
******************************************************************************************************/ 

#pragma once

// Item numbers for each item. 
//
// Use TCLGetItemPointer (ViewUtilities) to convert these
// item numbers to a pointer to the named item. 

enum
{

NewEntryDialog_Begin_. 
kNewEntryDialog_Stat1 = 1, 
kNewEntryDialog_Stat1ID =4097L, 
kNewEntryDialog_Stat2 =2, 
kNewEntryDialog_Stat2ID =4098L, 
kNewEntryDialog_Stat3 = 3, 
kNewEntryDialog_Stat3ID =4099L, 
kNewEntryDialog_Stat4 = 4, 
kNewEntryDialog_Stat4ID = 4100L, 
kNewEntryDialog_Stat5 = 5, 
kNewEntryDialog_Stat5ID = 4101L, 
kNewEntryDialog_Stat6 = 6, 
kNewEntryDialog_StatID6 = 4102L, 
kNewEntryDialog_Butn7 = 7, 
kNewEntryDialog_Butn7ID = 4103L, 
kNewEntryDialog_Butn8 =8, 
kNewEntryDialog_Butna = 4104L, 
kNewEntryDialog_Name =9, 
kNewEntryDialog_NameID =4105L, 
kNewEntryDialog_Adddress =10, 
kNewEntryDialog_AddressID =4106L, 
kNewEntryDialog_City =11, 
kNewEntryDialog_CityID = 4107L, 
kNewEntryDialog_State =12, 
kNewEntryDialog_StateID = 4108L, 
kNewEntryDialog_Zip = 13, 
kNewEntryDialog_ZipID = 4109L, 
kNewEntryDialog_Telephone = 14, 
kNewEntryDialog_TelephoneID =4110L, 
kNewEntryDialog_Stat15 = 15, 
kNewEntryDialog_Stat15ID = 4111L, 
NewEntryDialog_End_
};
